tabela = ('Palmeiras', 'Flamengo', 'Internacional', 'Grêmio', 'São Paulo', 'Atlético-MG', 'Atlético-PA', 'Cruzeiro', 'Botafogo', 'Santos', 'Bahia', 'Corinthians', 'Ceará', 'Fluminense', 'Vasco da Gama', 'Chapecoense', 'América Mineiro', 'Sport', 'Vitória', 'Paraná')
print(f'Lista de times do brasileirão 2018: {tabela}')
print('==' * 15)
print(f'Os 5 primeiros colocados são : {tabela[0:5]}')
print('==' * 15)
print(f'Os últimos 4 colocados são: {tabela[16:]}')
print('==' * 15)
print('Times em ordem alfabética: ', end='')
print(sorted(tabela))
print('==' * 15)
print(f'A Chapecoense está na {tabela.index("Chapecoense")+1}ª posição ')